# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20180108_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine',
            field=models.ManyToManyField(blank=True, to='pet.Vaccine'),
        ),
    ]
